### ISSUE TITLE
Data available for 25331360

### ISSUE THREAD

**Issue by abarysh** [baryshnikova-lab/YeastPhenome.org#76]
@ChristieChang I was looking into PMID 25331360 and had a couple of questions about the annotation you added:

- they say "We performed a genome-wide genetic screen for sensitivity to 100 μM CdCl2, using a collection of homozygous diploid yeast deletion mutants for 4757 nonessential yeast genes." -- but you indicated that the collection is hap a/alpha/hom (which means it's not clear if it's hap or hom). From the sentence above, it seems clear to me that it's hom. Did I miss some other info somewhere else in the paper? 
- you indicated data measured=quantitative, published=discrete, available=quantitative. Is it a typo? You mean, "available=discrete"?

I'm trying to figure out what info I should be requesting from them.

Thanks!

**Comment by ChristieChang** [comment]
I just corrected these errors. I think what must have happened is that I accidentally chose hap a/alpha/hom thinking that was equivalent to MATa/alpha/hom (I must have overlooked the hom option). And you're right, I meant "available=discrete". I must have interpreted "available" as "possibly available".

It also wasn't clear from this paper if the data measured was definitely quantitative. It references PMID 23026396, which states measuring colony size in what I believe should be a quantitative measurement. I see that you were working on this other PMID today, so I'm guessing that you added in PMID 23026396 because you saw it in this paper, but just wanted to make sure you made the connection (the two papers share an author, so you might want to contact them together).

**Comment by abarysh** [comment]
Yep, exactly, I was trying to figure out how they measured the colonies and found the other paper too. Thanks!
